// AUTO-GENERATED by icon-sync pipeline. DO NOT EDIT.

export interface IconMeta {
  title: string;
  slug: string;
  variant?: string;
  source: string;
  sourceVersion?: string;
  file: string;
  hex?: string;
}

export const iconManifest = [
  {
    "name": "adobe",
    "title": "Adobe",
    "slug": "adobe",
    "file": "adobe.svg",
    "source": "official-archive",
    "hex": "FF0000"
  },
  {
    "name": "amazonwebservices-original-wordmark",
    "title": "amazonwebservices",
    "slug": "amazonwebservices",
    "file": "amazonwebservices-original-wordmark.svg",
    "source": "devicon",
    "hex": "#f90"
  },
  {
    "name": "amd",
    "title": "AMD",
    "slug": "amd",
    "file": "amd.svg",
    "source": "simple-icons",
    "hex": "#ED1C24"
  },
  {
    "name": "angular",
    "title": "Angular",
    "slug": "angular",
    "file": "angular.svg",
    "source": "simple-icons",
    "hex": "#0F0F11"
  },
  {
    "name": "angular-2",
    "title": "angular",
    "slug": "angular",
    "file": "angular-2.svg",
    "source": "devicon",
    "hex": "#FFFFFF"
  },
  {
    "name": "anthropic",
    "title": "Anthropic",
    "slug": "anthropic",
    "file": "anthropic.svg",
    "source": "simple-icons",
    "hex": "#191919"
  },
  {
    "name": "apache",
    "title": "Apache",
    "slug": "apache",
    "file": "apache.svg",
    "source": "simple-icons",
    "hex": "#D22128"
  },
  {
    "name": "apache-2",
    "title": "apache",
    "slug": "apache",
    "file": "apache-2.svg",
    "source": "devicon",
    "hex": "#cb2533"
  },
  {
    "name": "apple",
    "title": "Apple",
    "slug": "apple",
    "file": "apple.svg",
    "source": "simple-icons",
    "hex": "#000000"
  },
  {
    "name": "apple-2",
    "title": "apple",
    "slug": "apple",
    "file": "apple-2.svg",
    "source": "devicon",
    "hex": "#000000"
  },
  {
    "name": "astro",
    "title": "Astro",
    "slug": "astro",
    "file": "astro.svg",
    "source": "simple-icons",
    "hex": "#BC52EE"
  },
  {
    "name": "astro-2",
    "title": "astro",
    "slug": "astro",
    "file": "astro-2.svg",
    "source": "devicon",
    "hex": "#ff5d01"
  },
  {
    "name": "cloudflare",
    "title": "Cloudflare",
    "slug": "cloudflare",
    "file": "cloudflare.svg",
    "source": "simple-icons",
    "hex": "#F38020"
  },
  {
    "name": "cloudflare-2",
    "title": "cloudflare",
    "slug": "cloudflare",
    "file": "cloudflare-2.svg",
    "source": "devicon",
    "hex": "#F38020"
  },
  {
    "name": "cplusplus",
    "title": "C++",
    "slug": "cplusplus",
    "file": "cplusplus.svg",
    "source": "simple-icons",
    "hex": "#00599C"
  },
  {
    "name": "cplusplus-2",
    "title": "cplusplus",
    "slug": "cplusplus",
    "file": "cplusplus-2.svg",
    "source": "devicon",
    "hex": "#004482"
  },
  {
    "name": "csharp",
    "title": "csharp",
    "slug": "csharp",
    "file": "csharp.svg",
    "source": "devicon",
    "hex": "#68217a"
  },
  {
    "name": "deepseek",
    "title": "DeepSeek",
    "slug": "deepseek",
    "file": "deepseek.svg",
    "source": "simple-icons",
    "hex": "#5786FE"
  },
  {
    "name": "discord",
    "title": "Discord",
    "slug": "discord",
    "file": "discord.svg",
    "source": "simple-icons",
    "hex": "#5865F2"
  },
  {
    "name": "docker",
    "title": "Docker",
    "slug": "docker",
    "file": "docker.svg",
    "source": "simple-icons",
    "hex": "#2496ED"
  },
  {
    "name": "docker-2",
    "title": "docker",
    "slug": "docker",
    "file": "docker-2.svg",
    "source": "devicon",
    "hex": "#019bc6"
  },
  {
    "name": "figma",
    "title": "Figma",
    "slug": "figma",
    "file": "figma.svg",
    "source": "simple-icons",
    "hex": "#F24E1E"
  },
  {
    "name": "figma-2",
    "title": "figma",
    "slug": "figma",
    "file": "figma-2.svg",
    "source": "devicon",
    "hex": "#f24e1e"
  },
  {
    "name": "git",
    "title": "Git",
    "slug": "git",
    "file": "git.svg",
    "source": "simple-icons",
    "hex": "#F03C2E"
  },
  {
    "name": "git-2",
    "title": "git",
    "slug": "git",
    "file": "git-2.svg",
    "source": "devicon",
    "hex": "#f34f29"
  },
  {
    "name": "github",
    "title": "GitHub",
    "slug": "github",
    "file": "github.svg",
    "source": "simple-icons",
    "hex": "#181717"
  },
  {
    "name": "github-2",
    "title": "github",
    "slug": "github",
    "file": "github-2.svg",
    "source": "devicon",
    "hex": "#181616"
  },
  {
    "name": "gitlab",
    "title": "GitLab",
    "slug": "gitlab",
    "file": "gitlab.svg",
    "source": "simple-icons",
    "hex": "#FC6D26"
  },
  {
    "name": "gitlab-2",
    "title": "gitlab",
    "slug": "gitlab",
    "file": "gitlab-2.svg",
    "source": "devicon",
    "hex": "#E24329"
  },
  {
    "name": "go",
    "title": "Go",
    "slug": "go",
    "file": "go.svg",
    "source": "simple-icons",
    "hex": "#00ADD8"
  },
  {
    "name": "go-2",
    "title": "go",
    "slug": "go",
    "file": "go-2.svg",
    "source": "devicon",
    "hex": "#00acd7"
  },
  {
    "name": "google",
    "title": "Google",
    "slug": "google",
    "file": "google.svg",
    "source": "simple-icons",
    "hex": "#4285F4"
  },
  {
    "name": "google-2",
    "title": "google",
    "slug": "google",
    "file": "google-2.svg",
    "source": "devicon",
    "hex": "#587dbd"
  },
  {
    "name": "googlecloud",
    "title": "Google Cloud",
    "slug": "googlecloud",
    "file": "googlecloud.svg",
    "source": "simple-icons",
    "hex": "#4285F4"
  },
  {
    "name": "googlecloud-2",
    "title": "googlecloud",
    "slug": "googlecloud",
    "file": "googlecloud-2.svg",
    "source": "devicon",
    "hex": "#557ebf"
  },
  {
    "name": "huggingface",
    "title": "Hugging Face",
    "slug": "huggingface",
    "file": "huggingface.svg",
    "source": "simple-icons",
    "hex": "#FFD21E"
  },
  {
    "name": "ibm",
    "title": "IBM",
    "slug": "ibm",
    "file": "ibm.svg",
    "source": "official-archive",
    "hex": "052FAD"
  },
  {
    "name": "intel",
    "title": "Intel",
    "slug": "intel",
    "file": "intel.svg",
    "source": "simple-icons",
    "hex": "#0071C5"
  },
  {
    "name": "java",
    "title": "java",
    "slug": "java",
    "file": "java.svg",
    "source": "devicon",
    "hex": "#EA2D2E"
  },
  {
    "name": "javascript",
    "title": "JavaScript",
    "slug": "javascript",
    "file": "javascript.svg",
    "source": "simple-icons",
    "hex": "#F7DF1E"
  },
  {
    "name": "javascript-2",
    "title": "javascript",
    "slug": "javascript",
    "file": "javascript-2.svg",
    "source": "devicon",
    "hex": "#f0db4f"
  },
  {
    "name": "kotlin",
    "title": "Kotlin",
    "slug": "kotlin",
    "file": "kotlin.svg",
    "source": "simple-icons",
    "hex": "#7F52FF"
  },
  {
    "name": "kotlin-2",
    "title": "kotlin",
    "slug": "kotlin",
    "file": "kotlin-2.svg",
    "source": "devicon",
    "hex": "#c711e1"
  },
  {
    "name": "kubernetes",
    "title": "Kubernetes",
    "slug": "kubernetes",
    "file": "kubernetes.svg",
    "source": "simple-icons",
    "hex": "#326CE5"
  },
  {
    "name": "kubernetes-2",
    "title": "kubernetes",
    "slug": "kubernetes",
    "file": "kubernetes-2.svg",
    "source": "devicon",
    "hex": "#326ce5"
  },
  {
    "name": "linkedin",
    "title": "linkedin",
    "slug": "linkedin",
    "file": "linkedin.svg",
    "source": "devicon",
    "hex": "#0076b2"
  },
  {
    "name": "linux",
    "title": "Linux",
    "slug": "linux",
    "file": "linux.svg",
    "source": "simple-icons",
    "hex": "#FCC624"
  },
  {
    "name": "linux-2",
    "title": "linux",
    "slug": "linux",
    "file": "linux-2.svg",
    "source": "devicon",
    "hex": "#000000"
  },
  {
    "name": "meta",
    "title": "Meta",
    "slug": "meta",
    "file": "meta.svg",
    "source": "simple-icons",
    "hex": "#0467DF"
  },
  {
    "name": "microsoft",
    "title": "Microsoft",
    "slug": "microsoft",
    "file": "microsoft.svg",
    "source": "official-archive",
    "hex": "00A4EF"
  },
  {
    "name": "mistralai",
    "title": "Mistral AI",
    "slug": "mistralai",
    "file": "mistralai.svg",
    "source": "simple-icons",
    "hex": "#FA520F"
  },
  {
    "name": "mongodb",
    "title": "MongoDB",
    "slug": "mongodb",
    "file": "mongodb.svg",
    "source": "simple-icons",
    "hex": "#47A248"
  },
  {
    "name": "mongodb-2",
    "title": "mongodb",
    "slug": "mongodb",
    "file": "mongodb-2.svg",
    "source": "devicon",
    "hex": "#4FAA41"
  },
  {
    "name": "mysql",
    "title": "MySQL",
    "slug": "mysql",
    "file": "mysql.svg",
    "source": "simple-icons",
    "hex": "#4479A1"
  },
  {
    "name": "mysql-2",
    "title": "mysql",
    "slug": "mysql",
    "file": "mysql-2.svg",
    "source": "devicon",
    "hex": "#00618a"
  },
  {
    "name": "netflix",
    "title": "Netflix",
    "slug": "netflix",
    "file": "netflix.svg",
    "source": "simple-icons",
    "hex": "#E50914"
  },
  {
    "name": "nextdotjs",
    "title": "Next.js",
    "slug": "nextdotjs",
    "file": "nextdotjs.svg",
    "source": "simple-icons",
    "hex": "#000000"
  },
  {
    "name": "nginx",
    "title": "NGINX",
    "slug": "nginx",
    "file": "nginx.svg",
    "source": "simple-icons",
    "hex": "#009639"
  },
  {
    "name": "nginx-2",
    "title": "nginx",
    "slug": "nginx",
    "file": "nginx-2.svg",
    "source": "devicon",
    "hex": "#090"
  },
  {
    "name": "nodedotjs",
    "title": "Node.js",
    "slug": "nodedotjs",
    "file": "nodedotjs.svg",
    "source": "simple-icons",
    "hex": "#5FA04E"
  },
  {
    "name": "notion",
    "title": "Notion",
    "slug": "notion",
    "file": "notion.svg",
    "source": "simple-icons",
    "hex": "#000000"
  },
  {
    "name": "notion-2",
    "title": "notion",
    "slug": "notion",
    "file": "notion-2.svg",
    "source": "devicon",
    "hex": "#fff"
  },
  {
    "name": "nuxt",
    "title": "Nuxt",
    "slug": "nuxt",
    "file": "nuxt.svg",
    "source": "simple-icons",
    "hex": "#00DC82"
  },
  {
    "name": "nuxt-2",
    "title": "nuxt",
    "slug": "nuxt",
    "file": "nuxt-2.svg",
    "source": "devicon",
    "hex": "#00dc82"
  },
  {
    "name": "nvidia",
    "title": "NVIDIA",
    "slug": "nvidia",
    "file": "nvidia.svg",
    "source": "simple-icons",
    "hex": "#76B900"
  },
  {
    "name": "postgresql",
    "title": "PostgreSQL",
    "slug": "postgresql",
    "file": "postgresql.svg",
    "source": "simple-icons",
    "hex": "#4169E1"
  },
  {
    "name": "postgresql-2",
    "title": "postgresql",
    "slug": "postgresql",
    "file": "postgresql-2.svg",
    "source": "devicon",
    "hex": "#336791"
  },
  {
    "name": "python",
    "title": "Python",
    "slug": "python",
    "file": "python.svg",
    "source": "simple-icons",
    "hex": "#3776AB"
  },
  {
    "name": "python-2",
    "title": "python",
    "slug": "python",
    "file": "python-2.svg",
    "source": "devicon",
    "hex": "#ffd845"
  },
  {
    "name": "react",
    "title": "React",
    "slug": "react",
    "file": "react.svg",
    "source": "simple-icons",
    "hex": "#61DAFB"
  },
  {
    "name": "react-2",
    "title": "react",
    "slug": "react",
    "file": "react-2.svg",
    "source": "devicon",
    "hex": "#61dafb"
  },
  {
    "name": "redis",
    "title": "Redis",
    "slug": "redis",
    "file": "redis.svg",
    "source": "simple-icons",
    "hex": "#FF4438"
  },
  {
    "name": "redis-2",
    "title": "redis",
    "slug": "redis",
    "file": "redis-2.svg",
    "source": "devicon",
    "hex": "#d82c20"
  },
  {
    "name": "rust",
    "title": "Rust",
    "slug": "rust",
    "file": "rust.svg",
    "source": "simple-icons",
    "hex": "#000000"
  },
  {
    "name": "rust-2",
    "title": "rust",
    "slug": "rust",
    "file": "rust-2.svg",
    "source": "devicon",
    "hex": "#000"
  },
  {
    "name": "slack",
    "title": "slack",
    "slug": "slack",
    "file": "slack.svg",
    "source": "devicon",
    "hex": "#2D333A"
  },
  {
    "name": "supabase",
    "title": "Supabase",
    "slug": "supabase",
    "file": "supabase.svg",
    "source": "simple-icons",
    "hex": "#3FCF8E"
  },
  {
    "name": "supabase-2",
    "title": "supabase",
    "slug": "supabase",
    "file": "supabase-2.svg",
    "source": "devicon",
    "hex": "#3ecf8e"
  },
  {
    "name": "svelte",
    "title": "Svelte",
    "slug": "svelte",
    "file": "svelte.svg",
    "source": "simple-icons",
    "hex": "#FF3E00"
  },
  {
    "name": "svelte-2",
    "title": "svelte",
    "slug": "svelte",
    "file": "svelte-2.svg",
    "source": "devicon",
    "hex": "#ff3e00"
  },
  {
    "name": "swift",
    "title": "Swift",
    "slug": "swift",
    "file": "swift.svg",
    "source": "simple-icons",
    "hex": "#F05138"
  },
  {
    "name": "swift-2",
    "title": "swift",
    "slug": "swift",
    "file": "swift-2.svg",
    "source": "devicon",
    "hex": "#F05138"
  },
  {
    "name": "tailwindcss",
    "title": "Tailwind CSS",
    "slug": "tailwindcss",
    "file": "tailwindcss.svg",
    "source": "simple-icons",
    "hex": "#06B6D4"
  },
  {
    "name": "tailwindcss-2",
    "title": "tailwindcss",
    "slug": "tailwindcss",
    "file": "tailwindcss-2.svg",
    "source": "devicon",
    "hex": "#38bdf8"
  },
  {
    "name": "tesla",
    "title": "Tesla",
    "slug": "tesla",
    "file": "tesla.svg",
    "source": "simple-icons",
    "hex": "#CC0000"
  },
  {
    "name": "typescript",
    "title": "TypeScript",
    "slug": "typescript",
    "file": "typescript.svg",
    "source": "simple-icons",
    "hex": "#3178C6"
  },
  {
    "name": "typescript-2",
    "title": "typescript",
    "slug": "typescript",
    "file": "typescript-2.svg",
    "source": "devicon",
    "hex": "#007acc"
  },
  {
    "name": "vercel",
    "title": "Vercel",
    "slug": "vercel",
    "file": "vercel.svg",
    "source": "simple-icons",
    "hex": "#000000"
  },
  {
    "name": "vercel-2",
    "title": "vercel",
    "slug": "vercel",
    "file": "vercel-2.svg",
    "source": "devicon",
    "hex": "#000"
  },
  {
    "name": "vite",
    "title": "Vite",
    "slug": "vite",
    "file": "vite.svg",
    "source": "simple-icons",
    "hex": "#9135FF"
  },
  {
    "name": "vite-2",
    "title": "vite",
    "slug": "vite",
    "file": "vite-2.svg",
    "source": "devicon",
    "hex": "#006BFF"
  },
  {
    "name": "vuedotjs",
    "title": "Vue.js",
    "slug": "vuedotjs",
    "file": "vuedotjs.svg",
    "source": "simple-icons",
    "hex": "#4FC08D"
  },
  {
    "name": "webpack",
    "title": "Webpack",
    "slug": "webpack",
    "file": "webpack.svg",
    "source": "simple-icons",
    "hex": "#8DD6F9"
  },
  {
    "name": "webpack-2",
    "title": "webpack",
    "slug": "webpack",
    "file": "webpack-2.svg",
    "source": "devicon",
    "hex": "#1C78C0"
  },
  {
    "name": "wechat",
    "title": "WeChat",
    "slug": "wechat",
    "file": "wechat.svg",
    "source": "simple-icons",
    "hex": "#07C160"
  },
  {
    "name": "x",
    "title": "X",
    "slug": "x",
    "file": "x.svg",
    "source": "simple-icons",
    "hex": "#000000"
  },
  {
    "name": "youtube",
    "title": "YouTube",
    "slug": "youtube",
    "file": "youtube.svg",
    "source": "simple-icons",
    "hex": "#FF0000"
  }
] as const;

export type IconName =
  | "adobe"
  | "amazonwebservices-original-wordmark"
  | "amd"
  | "angular"
  | "angular-2"
  | "anthropic"
  | "apache"
  | "apache-2"
  | "apple"
  | "apple-2"
  | "astro"
  | "astro-2"
  | "cloudflare"
  | "cloudflare-2"
  | "cplusplus"
  | "cplusplus-2"
  | "csharp"
  | "deepseek"
  | "discord"
  | "docker"
  | "docker-2"
  | "figma"
  | "figma-2"
  | "git"
  | "git-2"
  | "github"
  | "github-2"
  | "gitlab"
  | "gitlab-2"
  | "go"
  | "go-2"
  | "google"
  | "google-2"
  | "googlecloud"
  | "googlecloud-2"
  | "huggingface"
  | "ibm"
  | "intel"
  | "java"
  | "javascript"
  | "javascript-2"
  | "kotlin"
  | "kotlin-2"
  | "kubernetes"
  | "kubernetes-2"
  | "linkedin"
  | "linux"
  | "linux-2"
  | "meta"
  | "microsoft"
  | "mistralai"
  | "mongodb"
  | "mongodb-2"
  | "mysql"
  | "mysql-2"
  | "netflix"
  | "nextdotjs"
  | "nginx"
  | "nginx-2"
  | "nodedotjs"
  | "notion"
  | "notion-2"
  | "nuxt"
  | "nuxt-2"
  | "nvidia"
  | "postgresql"
  | "postgresql-2"
  | "python"
  | "python-2"
  | "react"
  | "react-2"
  | "redis"
  | "redis-2"
  | "rust"
  | "rust-2"
  | "slack"
  | "supabase"
  | "supabase-2"
  | "svelte"
  | "svelte-2"
  | "swift"
  | "swift-2"
  | "tailwindcss"
  | "tailwindcss-2"
  | "tesla"
  | "typescript"
  | "typescript-2"
  | "vercel"
  | "vercel-2"
  | "vite"
  | "vite-2"
  | "vuedotjs"
  | "webpack"
  | "webpack-2"
  | "wechat"
  | "x"
  | "youtube";
