// AUTO-GENERATED by icon-sync pipeline. DO NOT EDIT.
import React, { type SVGProps } from "react";
import type { IconName } from "./index";

export type { IconName };

/**
 * 通用品牌技术 Icon 组件
 * 支持自动匹配 SVG 资源路径与响应式宽高
 */
export interface IconProps extends SVGProps<SVGSVGElement> {
  name: IconName;
  size?: number | string;
  color?: string;
  className?: string;
  baseUrl?: string;
}

export const Icon: React.FC<IconProps> = ({
  name,
  size = 24,
  className = "",
  baseUrl = "/icons",
  ...props
}) => {
  return (
    <img
      src={`${baseUrl}/${name}.svg`}
      alt={`${name} icon`}
      width={size}
      height={size}
      className={className}
      loading="lazy"
      {...(props as any)}
    />
  );
};

export default Icon;
