// AUTO-GENERATED by icon-sync pipeline. DO NOT EDIT.
import { defineComponent, h, type PropType } from "vue";
import type { IconName } from "./index";

export type { IconName };

export const Icon = defineComponent({
  name: "BrandIcon",
  props: {
    name: {
      type: String as PropType<IconName>,
      required: true
    },
    size: {
      type: [Number, String],
      default: 24
    },
    baseUrl: {
      type: String,
      default: "/icons"
    }
  },
  setup(props, { attrs }) {
    return () =>
      h("img", {
        src: `${props.baseUrl}/${props.name}.svg`,
        alt: `${props.name} icon`,
        width: props.size,
        height: props.size,
        loading: "lazy",
        ...attrs
      });
  }
});

export default Icon;
